### ISSUE TITLE
Code in <details /> tags isn't properly formatted.

### ISSUE THREAD

**Issue by dbismut** [gregberge/smooth-doc#20]
## 🐛 Bug Report

In the code below, the `<pre>` tag enclosing the prism highlighted code won't receive proper styling.

````mdx
<details>
  <summary>Collapsible element</summary>
```jsx
console.log("hello")
```
</details>
````

## Suggested solution

https://github.com/gregberge/smooth-doc/blob/2b47cf7e6c7ebabd350e687cc7c200c17f51d7c7/smooth-doc/src/components/Article.js#L19

The problem in this situation is that `<pre>` is not a direct children of the `<Article>`. For lack of a generic solution for all nested code blocks, I think you should try to replace with:

```css
> pre, > summary > pre {
/* ... */
}
```

**Comment by gregberge** [comment]
OK, will submit a fix, thanks!
