### ISSUE TITLE
Direct link to docs shows blank page on mobile when in production / build mode

### ISSUE THREAD

**Issue by dbismut** [gregberge/smooth-doc#22]
Short note: I've been reporting several issues lately, and forgot to show my appreciation for this project. I also discovered xstyles which looks super promising! 

## 🐛 Bug Report

In production / build mode, accessing a docs page on mobile directly (without going through the homepage) shows a blank page.

## To Reproduce

Go here: https://use-gesture.netlify.app/docs/extras/ with a viewport width set to anything strictly under 768px.

## Expected behavior

The content of the page should show.

Note that this problem doesn't happen in development mode.

Here is a DOM extract in **development** mode (correct):

<img width="503" alt="development is ok" src="https://user-images.githubusercontent.com/5003380/97086264-75717100-1622-11eb-99fe-e487848d87ec.png">

Here is a DOM extract in **production** mode (incorrect):

<img width="443" alt="production is not ok" src="https://user-images.githubusercontent.com/5003380/97086339-de58e900-1622-11eb-8e6c-77cd68a16dd8.png">

As you can see, the class passed to the content `div` is incorrect in production mode (as they are the same as the sidebar). I wasn't able to trace down the problem.

## Link to repl or repo

This is a full-fleshed repo (that has code line highlights, and a properly working sidenav — see #17): 
https://github.com/pmndrs/react-use-gesture/tree/master/documentation

But any out-of-the box updated repro with a correct 404 page (see #21) will show the same problem.

## Run `npx envinfo --system --binaries --npmPackages smooth-doc,gatsby,react,react-dom --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
 - Memory: 99.66 MB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
## npmPackages:
 - gatsby: ^2.24.85 => 2.24.85 
 - react: ^17.0.1 => 17.0.1 
 - react-dom: ^17.0.1 => 17.0.1 
 - smooth-doc: ^5.1.1 => 5.1.1 
```

**Comment by dbismut** [comment]
I've managed to narrow down the issue to these lines:

https://github.com/gregberge/smooth-doc/blob/2b47cf7e6c7ebabd350e687cc7c200c17f51d7c7/smooth-doc/src/components/DocLayout.js#L186-L190

Commenting them out fixes the issue (but you lose the mobile menu).

**Comment by gregberge** [comment]
Hmm I will give a look, thanks.
