### ISSUE TITLE
Nav bar shows overflow for no reason on small screens

### ISSUE THREAD

**Issue by dbismut** [gregberge/smooth-doc#24]
## 🐛 Bug Report

Nav shows overflow for no reason on small resolutions.

<img width="637" alt="Capture d’écran 2020-10-25 à 17 25 50" src="https://user-images.githubusercontent.com/5003380/97112937-66082b80-16e7-11eb-8246-64cb4092b9c1.png">

The fix is pretty easy, commenting out this line fixes it:

https://github.com/gregberge/smooth-doc/blob/2b47cf7e6c7ebabd350e687cc7c200c17f51d7c7/smooth-doc/src/components/Nav.js#L57

**Comment by gregberge** [comment]
Hello @dbismut, thanks, I will give a look to it!
