### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by ryexley** [gregberge/smooth-doc#25]
## 🐛 Bug Report

First of all, I'd like to say what a nice job you've done with smooth DOC. Really like, helpful utility, and I'm excited to get up-and-running with it. I feel like I'm super close, but am running into one issue. I'm sure it's something simple, but I'm having trouble figuring out exactly what the issue is.

I've created a new site following the "Getting Started" instructions. Everything worked fine, and it ran with no issues with the default setup. Then I added a couple of docs pages in the `/docs` folder, and that's when things went wrong. 

## To Reproduce

1. Generate a new site following the "Getting Started" instructions
2. Add a new page at `/pages/docs/code-review.mdx` with the following content:
```mdx
---
title: The Code Review Process
section: Code
---

# The Code Review Process

TODO

```
3. Add a new page at `/pages/docs/coding-standards.mdx` with the following content:
```mdx
---
title: Coding Standards
section: Code
---

# Coding Standards

TODO

## JavaScript

TODO

## React

TODO

## Python

TODO

## Go

TODO

```
4. Restart the `develop` task in the terminal (this is actually a secondary part of the issue, I was expecting these browser to show these new pages, as I could see the terminal process recognized that they were there, and it processed them, but when I manually refreshed the browser, nothing changed).

## Expected behavior

I expected to see these two new pages displayed in the sidebar navigation, and be able to navigate to and view them.

## Actual behavior

After manually restarting the process (which runs without any errors) and refreshing my browser, I see the following error stack:

![image](https://user-images.githubusercontent.com/173844/97588851-49177500-19d3-11eb-9a79-fecaf9f8d7c0.png)

## Run `npx envinfo --system --binaries --npmPackages smooth-doc,gatsby,react,react-dom --markdown --clipboard`

Paste the results here:

```bash

## System:
 - OS: macOS 10.15.6
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 715.18 MB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
## npmPackages:
 - gatsby: ^2.15.18 => 2.24.91 
 - react: ^16.10.1 => 16.14.0 
 - react-dom: ^16.10.1 => 16.14.0 
 - smooth-doc: ^5.0.4 => 5.2.0 

```

**Comment by roadsenseik** [comment]
Did you manage to solve this problem?
I'm facing this problem too when I'm creating 2+ sections
