### ISSUE TITLE
Blog Index Page

### ISSUE THREAD

**Issue by lunchboxav** [gregberge/smooth-doc#31]
Hi there. First of all, thank you so much for the great project. I'm using smooth doc for an upcoming project and it suits my needs. However, I have a question. I'm adding blog pages to my docs site. Implementation wise, I just add them as normal pages under a new `posts` directory. That works for the time being. 

However, I'm trying to add a blog index page that lists down all the pages under that `posts` directory, but I'm unable to do so. I can't query graphql from a an `.mdx` file. I also tried to do it on createPage in gatsby-node.js, but it doesn't work either, because it seems like it doesn't fit the `pageType` asked in `PageWrapper.js`.

Is there any approach that I can take to reach this goal? 

Thank you very much.

**Comment by gregberge** [comment]
Hello @lunchboxav, it could be a good addition to this project to have a blog section. For now I don't have a good solution except adding some method to your `gatsby-*.js` to try to do something.
