### ISSUE TITLE
UI for multiple products/ projects

### ISSUE THREAD

**Issue by adarshbm11** [gregberge/smooth-doc#33]
## 🚀 Feature Proposal

Add four more pages using the same layout, each with separate sideNav.  Users should be able to access the respective docs from the topNav (preferably a dropdown)

Docs 
 Product 1
 Product 2

Search integration: elasticlunr/ lunr

## Example
[](https://adarshbm11.github.io/Expdocs/) 

(See menu items (Products/ Dev docs from the top nav. Screenshot attached)

![image](https://user-images.githubusercontent.com/65062532/105463885-b37c4080-5cb6-11eb-9917-c9c2480fccd6.png)

**Comment by gregberge** [comment]
Smooth Docs is opinionated and target simple docs. If you want to build a custom website, then you should use Gatsby or Next.js and build you own template.
