### ISSUE TITLE
Plain markdown (.md) support

### ISSUE THREAD

**Issue by fwouts** [gregberge/smooth-doc#37]
## 🚀 Feature Proposal

Add support for .md files, in addition to .mdx.

## Motivation

Since the MDX format is quite new, most Markdown text editors (such as [Typora](https://typora.io)) don't support it.

This would generally be useful for pages where you don't need to include any custom React components, which can be the majority of pages when you're writing basic documentation.

## Example

If I create a file `docs/index.md`, it should automatically be served when loading `/docs`.

## Pitch

Markdown is the foundation on which MDX is built, therefore it makes sense to support it :)

**Comment by gregberge** [comment]
Fixed in #39
