### ISSUE TITLE
Previous/next page navigation disappears when using --prefix-paths

### ISSUE THREAD

**Issue by fwouts** [gregberge/smooth-doc#41]
## 🐛 Bug Report

When using `gatsby build --prefix-paths` to serve the documentation website under a prefix such as `/my-project/`, the previous/next links at the bottom of each page disappear.

Note that other types of navigation don't seem to be affected.

## To Reproduce

See https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/

1) Add `pathPrefix: "/hello"` to `gatsby-config.js`
2) Run `gatsby build --prefix-paths`
3) Run `gatsby serve --prefix-paths` and navigate to `http://localhost:8000/hello`
4) Notice that previous/next links are missing at the bottom of each page.

## Expected behavior

The previous/next links should still appear, and have the expected prefix.

## Link to repl or repo (highly encouraged)

https://github.com/fwouts/smooth-doc-starter/compare/master...fwouts:path-prefix-bug

Compare running:
```
yarn gatsby build && yarn gatsby serve # works fine
yarn gatsby build --prefix-paths && yarn gatsby serve --prefix-paths # no navigation
```

## Run `npx envinfo --system --binaries --npmPackages smooth-doc,gatsby,react,react-dom --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 11.2.1
 - CPU: (8) arm64 Apple M1
 - Memory: 109.27 MB / 8.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 15.8.0 - /opt/homebrew/bin/node
 - Yarn: 1.22.10 - /opt/homebrew/bin/yarn
 - npm: 7.5.0 - /opt/homebrew/bin/npm
## npmPackages:
 - gatsby: ^2.15.18 => 2.32.4
 - react: ^16.10.1 => 16.14.0
 - react-dom: ^16.10.1 => 16.14.0
 - smooth-doc: ^5.0.4 => 5.5.0
```

**Comment by fwouts** [comment]
I should note that I'm happy to send out a PR to fix this, given a few pointers to the right area of the code 🙂

**Comment by gregberge** [comment]
Hello @fwouts, sorry for the delay, you can find some hint here: https://github.com/gregberge/smooth-doc/blob/829a450c66d1d89fb15cb3e2749e4edc51411015/smooth-doc/src/components/SideNav.js#L125-L142
