### ISSUE TITLE
make algolia appId configurable

### ISSUE THREAD

**Issue by msvechla** [gregberge/smooth-doc#51]
## 🚀 Feature Proposal

We are running [Algolia on our own](https://docsearch.algolia.com/docs/run-your-own) and therefore need to configure our own `appId`when setting up search. I would propose to make this parameter configurable as well.

## Motivation

Allow "run your own" config for algolia as well.

more info here: https://docsearch.algolia.com/docs/run-your-own#integration

**Comment by gregberge** [comment]
Hello @msvechla, feel free to submit a PR for that.
