### ISSUE TITLE
Sharp package needs a tar file installation/extraction that connects to github 

### ISSUE THREAD

**Issue by sayokbose91** [gregberge/smooth-doc#53]
## 💬 Questions and Help

npm i on smooth-doc starter fails for me as it is dependant on sharp packages...

when i see the log it says that sharp has some installation scripts that download a tar file from Github...

my company doesn't allow me to connect to GitHub and we have our own package manager within...
is there any option how we can run smooth-doc with a local installation?

**Comment by gregberge** [comment]
No there is not, blocking GitHub is not a good choice. If your company want to be alone, then they should build their own documentation theme 😅
