### ISSUE TITLE
install this theme of start,something is wrong

### ISSUE THREAD

**Issue by subutay** [gregberge/smooth-doc#59]
info Creating new site from git:
https://github.com/gregberge/smooth-doc-starter.git

Cloning into 'website'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 16 (delta 1), reused 13 (delta 1), pack-reused 0
Receiving objects: 100% (16/16), 366.55 KiB | 1.49 MiB/s, done.
success Created starter directory layout
info Installing packages...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: smooth-doc-starter@0.0.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.10.1" from the root project
npm ERR!   peer react@"^16.4.2 || ^17.0.0" from gatsby@2.32.13
npm ERR!   node_modules/gatsby
npm ERR!     gatsby@"^2.15.18" from the root project
npm ERR!     peer gatsby@"^2.15.0" from smooth-doc@5.5.0
npm ERR!     node_modules/smooth-doc
npm ERR!       smooth-doc@"^5.0.4" from the root project
npm ERR!   1 more (react-dom)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0 | ^17.0.0" from smooth-doc@5.5.0
npm ERR! node_modules/smooth-doc
npm ERR!   smooth-doc@"^5.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sunfeipo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

 ERROR 

Command failed with exit code 1: npm install

  Error: Command failed with exit code 1: npm install
  
  - error.js:60 makeError
    [21aee85bd6ee71e0]/[execa]/lib/error.js:60:11
  
  - index.js:118 handlePromise
    [21aee85bd6ee71e0]/[execa]/index.js:118:26
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
  
  - init-starter.js:135 install
    [21aee85bd6ee71e0]/[gatsby-cli]/lib/init-starter.js:135:7
  
  - init-starter.js:202 clone
    [21aee85bd6ee71e0]/[gatsby-cli]/lib/init-starter.js:202:3
  
  - init-starter.js:343 initStarter
    [21aee85bd6ee71e0]/[gatsby-cli]/lib/init-starter.js:343:5
  
  - create-cli.js:489 
    [21aee85bd6ee71e0]/[gatsby-cli]/lib/create-cli.js:489:9

I used the following commands in two places to install and test. One is a macbook and the other is aws, both of which have errors. How to do it?
npx gatsby-cli new website https://github.com/gregberge/smooth-doc-starter

**Comment by gregberge** [comment]
I don't provide support on installation sorry.
