### ISSUE TITLE
Custom HTML

### ISSUE THREAD

**Issue by matkoch** [gregberge/smooth-doc#60]
Hi @gregberge!

First of all, very great project! This template brings a lot of essential and effective features that I expect from modern documentation websites. I'm currently looking into porting the documentation for my own OSS project. Since I have almost no background with frontend frameworks, I might have a couple of noobie questions. I hope you don't mind 😅

My first immediate question is how I can add custom HTML to `mdx` files. Currently, when I add `<pre><code><span class="keyword">public</span></code></pre>` besides other content, I'm getting an error:

<img width="659" alt="Firefox-Getting Started2 - Smooth DOC-2022-01-22-rKY2C2qd" src="https://user-images.githubusercontent.com/5005566/150653307-f5bb410a-f3cc-4788-b8c9-282c927c7f2f.png">

(I know there is code highlighting built-in, but I have a custom tool that can generate better results for C# code)

I _guess/hope_ there's an easy way to make this work, but like I said: Gatsby, React, et al. are all very new to me.

Thanks in advance and keep up the good work!

**Comment by NehaK275** [comment]
Hi @matkoch can i solve this
